// Code generated by command: go run asm.go -pkg simd -out ../match.s -stubs ../match_amd64.go. DO NOT EDIT.

//go:build amd64

#include "textflag.h"

// func MatchMetadata(metadata *[16]uint8, hash uint8) uint16
// Requires: SSE2, SSSE3
TEXT ·MatchMetadata(SB), NOSPLIT, $0-18
	MOVQ     metadata+0(FP), AX
	MOVBLZX  hash+8(FP), CX
	MOVD     CX, X0
	PXOR     X1, X1
	PSHUFB   X1, X0
	MOVOU    (AX), X1
	PCMPEQB  X1, X0
	PMOVMSKB X0, AX
	MOVW     AX, ret+16(FP)
	RET

// func MatchEmpty(metadata *[16]uint8) uint16
// Requires: SSE2
TEXT ·MatchEmpty(SB), NOSPLIT, $0-10
	MOVQ     metadata+0(FP), AX
	PXOR     X0, X0
	MOVOU    (AX), X1
	PCMPEQB  X1, X0
	PMOVMSKB X0, AX
	MOVW     AX, ret+8(FP)
	RET
