// Code generated by command: go run asm.go -pkg simd -out ../match.s -stubs ../match_amd64.go. DO NOT EDIT.

//go:build amd64

package simd

// MatchMetadata performs a 16-way probe of |metadata| using SSE instructions
// nb: |metadata| must be an aligned pointer
func MatchMetadata(metadata *[16]uint8, hash uint8) uint16

// MatchMetadata performs a 16-way probe of zero byte using SSE instructions
// nb: |metadata| must be an aligned pointer
func MatchEmpty(metadata *[16]uint8) uint16
